version: '3'

services:

#  case:
#    image: case-study
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: case-study
      MYSQL_DATABASE: case_study
    ports:
      - '3306:3306'

volumes:
  case_study: